### PR TITLE
Move typescript to dep instead of devDep

### PR DESCRIPTION
**Pull request by paladox**
I think this is the cause of the failures when running gerrit's tests.

See https://bugs.chromium.org/p/gerrit/issues/detail?id=7683

### CODE REVIEW

**Comment by samccone** [comment]
Oh fun. Thanks for the PR @paladox

**Comment by paladox** [comment]
Thanks and your welcome :).

**Comment by paladox** [comment]
Hmm

npm WARN tsickle@0.23.6 requires a peer of typescript@2.3.4 but none is installed. You must install peer dependencies yourself.

complains now.

**Comment by paladox** [comment]
Hopping that will be fixed in https://github.com/angular/tsickle/pull/647 too.

**Comment by paladox** [comment]
Though i belive this change fixes it. It at least works with the tests again :).

**Pull request merged**
